### ISSUE TITLE
Enable sound on first interaction as an option

### ISSUE THREAD

**Issue by fpspad** [cloudpilot-emu/cloudpilot-emu#27]
Would it be possible to add a setting that allows sound to be on by default?  I always turn it on and appreciate getting bothered by the alarms. 

Thank you for such an awsome emulator. 

Frank. 

Ps. 

Also curious if it will ever be possible to keep the emulator running in the background on the phone. 

Thanks again!

**Comment by DirtyHairy** [comment]
Hi @fpspad !

> Would it be possible to add a setting that allows sound to be on by default?

I am afraid that automatically turning on audio on startup cannot work because browsers implement a policy that enabling web audio must happen as the result of a user interaction. However, what *would* be possible is to automatically start audio on the first interaction (touch, click, etc.). I've modified the title of the issue accordingly.

> Also curious if it will ever be possible to keep the emulator running in the background on the phone.

No, I am afraid not. Web applications cannot run in the background, and iOS even forbids extended background activity even for native apps.

> Thank you for such an awsome emulator.

Thanks alot 😏

**Comment by DirtyHairy** [comment]
Implemented and available for testing in the preview build.
