### ISSUE TITLE
Configurable snapshot interval

### ISSUE THREAD

**Issue by lxgr** [cloudpilot-emu/cloudpilot-emu#36]
Is there a reason the default snapshot interval is as high as it is (i.e. 1 Hz)?

If there is a reliable way to write it just before the PWA terminates (not sure if iOS offers an API/event for that?), much less frequent saves might be enough in most scenarios, unless that itself makes individual snapshots/diffs too large and ends up hurting performance more than it helps.

**Comment by DirtyHairy** [comment]
I want the experience to be as seamless as possible, hence 1Hz --- it creates the illusion of continuous persistence, and I haven't noticed any hit on the perceived power draw (or on raw performance). In principle there is a `visibilitychange` event that could be hooked for just-in-time saves, but I could not find any reliable information on the circumstances under which it is triggered, and how it behaves with async tasks (like indexeddb access). This could mean data loss, and that somewhat is my prime directive here: no data loss, under any circumstance 😏 

Do you have any specific issue with the snapshot interval?

**Comment by lxgr** [comment]
No specific issue, just a vague sense of anxiety around NAND wear!

But if it worked for Palm themselves on the Tungsten 5 and the other NAND-based devices, I guess I'll live 😅 (Although I think they only persisted upon closing an application?)

**Comment by DirtyHairy** [comment]
😆 I worried about the same thing, and that's why I try to keep the impact on new features on savestate size as small as possible. But if you do the numbers: an individual state save is something like 50kB (probably less), so that's about 180MB per hour. If this is war levelled over 10GB you get every cell written once every 55 hours. Assuming 10000 cycles lifetime that's something like 60 years of continuous Cloudpilot use --- we'll either be dead of old age or using neural implants by then 😏
