### ISSUE TITLE
App crashes on CloudPilot after working perfectly for one year – update problem?

### ISSUE THREAD

**Issue by danbae56** [cloudpilot-emu/cloudpilot-emu#45]
I have been using CloudPilot for iOS for over a year now, and my main reason for using it is that I want to use the Palm app Documents To Go, which syncs handheld editable word processor documents with Word documents on the desktop. This has been working perfectly since the start, but the last days, crashes have occurred which seem to be triggered by pasting copied/cut text from one part of a document to another. Initially, only one document is affected, but after a little while all documents belonging to the app crash upon opening with a "Fatal Alert " message, see enclosed image. The only way to get out of that has been to perform a hard reset, with data loss and cumbersome restoration procedures to go with it.

Now I don't expect you to be able to answer questions about this particular app, of course. But the sudden appearance of multiple instances of the same issue makes me wonder if there has been some recent update to CloudPilot that could have caused this behaviour. And would it be possible to revert to an earlier version, to check if the issue goes away?

Emulated device: Tungsten W
PalmOS: 4.1
CloudPilot: 1.7.11 iOS
iOS: 16.2
Hardware: iPhone SE

Most likely completely unrelated, but my CloudPilot Server certificate expired and had to be renewed immediately before these issues started to occur.

Also note that the error message in the image is not the one showed upon the first crash (the one seemingly caused by the paste action) – unfortunately I did not take a screenshot of that one, but it mentioned some index being out of range...

![image](https://user-images.githubusercontent.com/55235058/217520595-7c8348ce-61f4-46e4-8032-88fcd52ca2ec.png)

**Comment by DirtyHairy** [comment]
Hi Dan!

The crashes you encounter are either a bug in d2g or a sign if heap corruption on the emulated device. One way to trigger it fro d2g would be an attempt to write to the storage heap beyond the boundaries of a record, which may be a "legit" bug. However, the fact that it affects other d2g documents makes me suspicious, too.

I guess you are using the stable version of CP? While I have made quite a few updates to the 1.7.x branch, most of them are purely cosmetic and do not touch the core in any way. However, there has been one update (1.7.7) on nov 20th that fixes a nasty bug that could have caused corruption: previously, opening the emulator in two tabs simultaneously could corrupt the heap, even though CP stops with a message. Is this a virtual device that you created in a version that is older than 1.7.7? Did you ever get the "Cloudpilot is opened in another tab..." message with it? If so, you might have a corrupted heap.

How do you restore the device? If you restore a snapshot, than any previous heap corruption will remain. In order to make sure that this is not happening, export a backup instead ("Save Backup" from the menu), create a new device and install the resulting .zip (which contains all your databases as .pdb and .prc files) into the new device. After a soft reset you should have n almost exact clone, but with a freshly initialised heap. You could also try another highres device (i.e. a Sony PEG T675) on order to rule out a bug in the T|W ROM (although I think this is highly unlikely).

If the issue persists (and there is nothing too personal in those documents), could you send me a snapshot of the "corrupted" device so I can try to find out a bit more of what the specific error condition is?

Have you enable clipboard integration?

There is no straightforward way to go back to an older version, but I could put up an older build for you that you can try out. Iirc there were no changes to the save format in 1.7.x, so you should be able to load you devices there just fine. However, I can't see any change in 1.7.x that could have caused corruption.

**Comment by danbae56** [comment]
Hi Christian!

Thanks for the reply.

As for "stable version", I installed CP more than a year ago and since then I haven't done anything about it other than accept automatic update queries (the little dialog box saying a new version is available and do I want to install it). So, as I guess only stable versions are distributed that way, my version should be stable? As I said, it is currently 1.7.11 for iOS.

After the crashes, I have done hard reset and re-installed 3rd-party apps, then done HotSync to restore the databases as they were last saved. I would think that is pretty much the same thing as creating a new device? If there is a new crash, I could try out your method. The problem is that I don't have the habit of making backups that often; I rely more on HotSync (since I work with the documents also on my computer).

I can send you a snapshot if there is a new crash, assuming the snapshot feature is still available for a crashed device (snapshots are taken by swiping the session right and tapping the "Share" symbol, right?).

Yes clipboard integration is enabled.

Thanks for the offer of an older version – but let's put that on standby for the moment. Hopefully this was caused by a freak corruption of one document, which I now have sanitised, I think. If not I'll send you a snapshot.

**Comment by DirtyHairy** [comment]
Hi Dan!

Yeah, that's the stable version you're running, Indeed, hard resetting will also restore the heap to a sane state, so you issue is not being caused by previous heap corruption.

Saving a snapshot works exactly as you described thanks!

Are you copying anything unusal from the clipboard, i.e. weird Unicode characters?
