### ISSUE TITLE
Frobnitz

### ISSUE THREAD

**Issue by EdWinds11** [cloudpilot-emu/cloudpilot-emu#57]
Frobnitz installs and runs correctly, but when trying to load a game it crashes with the error, 0x8002.

https://frobnitz.sourceforge.net/

Thanks

**Comment by DirtyHairy** [comment]
HI @EdWinds11 !

The included story works fine for me on a virtual m515. What device and story are you using?

<img width="494" alt="image" src="https://github.com/cloudpilot-emu/cloudpilot-emu/assets/2444224/0ce46307-61fb-4968-8ad5-2029d8effb7a">

**Comment by EdWinds11** [comment]
I am using the Palm IIIc Color English 3.5 rom.  I will try the M515 rom and see what happens, thanks so much!

**Comment by EdWinds11** [comment]
Thank you so much, that fixed the problem and Frobnitz works perfectly now.

**Comment by DirtyHairy** [comment]
I see, reproduced it with a Palm IIIc / 3.5 ROM. Yeah, this looks like a bug (or an incompatibility) in frobnitz to me. Have fun on the m515 😏

**Comment by EdWinds11** [comment]
When I used to have a real Palm IIIc, Frobnitz always worked.

**Comment by DirtyHairy** [comment]
I tried a few ROMs, this version of Frobnitz seems to fail on all ROMs < OS4. Maybe your IIIc was running OS4 (it works on IIIc / OS4), or you were using an older version of Frobnitz. It is very unlikely that this error is caused by a bug in Cloudpilot, unless Frobnitz does some exotic hardware access, which it has not reason to do.
